version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: moneyTracker-backend
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - moneytracker-network

  db:
    image: postgres:latest
    restart: always
    container_name: moneyTracker-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - moneytracker-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  moneytracker-network:
    driver: bridge

volumes:
  postgres-data: